# https://travis-ci.org/

language: java
jdk: oraclejdk8

env:
    global:
        # Memory limit: 2Go
        - export JAVA_OPTS=-Xmx1g

before_install:
    # VersionEye
    # Disabled: - mvn versioneye:update
    
    # Codecov.io: install
    - pip install --user codecov

#install: # Default: `mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V`

# Override: add integration-test Maven phase
script: # Default: `mvn test -B`
    # Spring-Boot: external config: use "spring.application.json" command line argument
    - mvn -B -Dspring.application.json="$SPRING_APPLICATION_JSON" verify
    
    # Site: generate
    # Disabled: - mvn site

# Reporting
after_success:
    # JaCoCo: workaround: Maven `jacoco:report@post-integration-test` goal not working
    - mvn verify -DskipTests -B
    
    # Coveralls.io: publish
    - mvn coveralls:report
    # Codecov.io: publish
    - codecov

# Information about failure
after_failure:
    # show memory usage again
    - sudo free -m -t
    # show actions of the OOM killer
    - sudo dmesg

# Deploy
after_script:
    # Database upgrade
    - mvn liquibase:update -pl jsfring-database
    
    # Heroku: each application
    - mvn -DskipTests heroku:deploy -pl jsfring-batch-admin
    - mvn -DskipTests heroku:deploy -pl jsfring-webservice
    - mvn -DskipTests heroku:deploy -pl jsfring-webapp-angularjs
    - mvn -DskipTests heroku:deploy -pl jsfring-webapp-angular2
    - mvn -DskipTests heroku:deploy -pl jsfring-webapp-jsf
    
    # Site: GitHub pages
    # Disabled: - mvn --non-recursive com.github.github:site-maven-plugin:site
