# https://travis-ci.org/

language: java
jdk: oraclejdk8

env:
    global:
        # Memory limit: 2Go
        - export JAVA_OPTS=-Xmx1g

before_install:
    # Versionning
    - mvn versions:display-dependency-updates
    - mvn versions:display-plugin-updates
    - mvn versions:display-property-updates

# Override: `mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V`
install: true

# Override: `mvn test -B`
script:
    - mvn clean install -B
    
    # Documentation: generate site
    # Disabled: - mvn site

# Reporting
after_success:
    # Coveralls.io: publish
    - mvn coveralls:report
    # Codecov.io: publish
    - bash <(curl -s https://codecov.io/bash)

# Information about failure
after_failure:
    # show memory usage again
    - sudo free -m -t
    # show actions of the OOM killer
    - sudo dmesg

# Deploy
after_script:
    # Documentation: GitHub pages site
    # Disabled: - mvn --non-recursive com.github.github:site-maven-plugin:site
    
    # Database: Liquibase upgrade
    - mvn liquibase:update -pl jsfring-database
    
    # Application: Heroku
    - mvn -DskipTests heroku:deploy -pl jsfring-batch-admin
    - mvn -DskipTests heroku:deploy -pl jsfring-webservice
    - mvn -DskipTests heroku:deploy -pl jsfring-webapp-angularjs
    - mvn -DskipTests heroku:deploy -pl jsfring-webapp-angular2
    - mvn -DskipTests heroku:deploy -pl jsfring-webapp-jsf
