# Note: "external config" = requires to be set by external configuration
# See: https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html

spring:
    aop:
        # Disable proxies
        auto: false
        proxy-target-class: false
    #data.mongodb.uri: external config
    datasource:
        #url: external config
    jpa:
        hibernate:
            # Lower/underscore conversion of table/column name
            naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
        properties:
            hibernate:
                default_schema: public
                dialect: org.hibernate.dialect.PostgreSQL9Dialect
                format_sql: true
                #globally_quoted_identifiers: true
                use_sql_comments: false
        show-sql: true
    mail:
        #host: external config
        #password: external config
        #port: external config
        properties:
            mail.smtp.auth: true
            mail.smtp.starttls.enable: true
            #mail.smtp.ssl.trust: smtp.gmail.com
        test-connection: false
        #username: external config
